Add canary tests
aws-observability/aws-otel-collector-test-framework pull request #128
Opened 2020-11-25 01:05 UTC by shaochengwang

**Description:**
Add canary tests

**Tests done:**
1. Tested each test case locally in `shaochengwang/aws-otel-test-framework` e.g.
```
cd terraform/canary && terraform init && terraform apply -auto-approve -lock=false -var-file="../testcases/otlp_trace/parameters.tfvars" -var="aoc_version=latest" -var="testcase=../testcases/otlp_trace" -var="testing_ami=canary_windows"
```
2. Tested with GitHub workflow in ` shaochengwang/aws-otel-collector`

2020-11-25 17:00 UTC, wyTrivail requested changes
thanks!

2020-11-25 17:00 UTC, wyTrivail commented on terraform/canary/common.auto.tf
> +variable "region" {
this file is a symlink to the common.tf, you don't need to really add content for it. just create a symlink instead

2020-11-25 17:00 UTC, wyTrivail commented on terraform/canary/main.tf
> +  canary = var.canary
i guess canary will always equal to true here?

2020-11-25 17:00 UTC, wyTrivail commented on terraform/ec2/variables.tf
> +variable "canary" {
maybe give a comment here to explain the meaning of the "canary" var?

2020-11-25 17:00 UTC, wyTrivail commented on validator/src/main/java/com/amazon/aoc/App.java
> +      maxValidationCycles = 30;
any possibility we can write this part of logic in a separate method?

2020-11-25 17:00 UTC, wyTrivail commented on validator/src/main/java/com/amazon/aoc/App.java
> +            cloudWatchService.putMetricData("Otel/Canary", "Success", 0.0);
any dimension?

2020-11-25 17:00 UTC, wyTrivail commented on validator/src/main/java/com/amazon/aoc/App.java
> +      maxValidationCycles = 30;
how long does it take to run a round of canary, there's a limit on github that a job can only be running for no more than 6 hours.

2020-11-25 17:00 UTC, wyTrivail commented on validator/src/main/java/com/amazon/aoc/validators/MetricValidator.java
> +          if (!context.isCanary()) {
i guess you don't need to skip this check now, we changed the metric template.

2020-11-25 18:44 UTC, shaochengwang commented on validator/src/main/java/com/amazon/aoc/App.java
> +            cloudWatchService.putMetricData("Otel/Canary", "Success", 0.0);
Previously, I included `testingId` as one dimension, but then I found we cannot set alarm if the each run generates a different metric. I think canary tag is included in the namespace. What other information do we need for dimension?

2020-11-25 18:45 UTC, shaochengwang commented on validator/src/main/java/com/amazon/aoc/App.java
> +      maxValidationCycles = 30;
30, 31 minutes

2020-11-26 00:06 UTC, wyTrivail approved these changes
lgtm

2020-11-26 00:07 UTC, merged