Add soaking and perf to prometheus static
aws-observability/aws-otel-collector-test-framework pull request #150
Opened 2020-11-30 23:09 UTC by amanbrar1999

This PR is branched off of https://github.com/aws-observability/aws-otel-test-framework/pull/146 and heavily based on https://github.com/aws-observability/aws-otel-test-framework/pull/144. This should wait until both of those are merged. 

This simply adds configs needed to run performance and soaking tests using the prometheus static config, whereas previously only the mock case was supported

I have also moved `cortex_instance_endpoint` to be defined in the `common.tf` file since it is to be shared across multiple platforms, it can be specified there and can be overwritten if need be in individual `parameters.tfvars` files

2020-12-01 23:22 UTC, wyTrivail requested changes
this pr seems similar to https://github.com/aws-observability/aws-otel-test-framework/pull/146/files?

2020-12-01 23:22 UTC, wyTrivail commented on terraform/ec2/main.tf
> +      local.selected_ami["family"] == "amazon_linux" ? "sudo chmod 777 /opt/aws/aws-otel-collector/etc/.env && sudo echo 'SAMPLE_APP_HOST=${aws_instance.sidecar.public_ip}' >> /opt/aws/aws-otel-colle
the same comment, could you move it into the ami family def

2020-12-02 22:23 UTC, wyTrivail commented
can this pr be closed?

2020-12-03 00:09 UTC, amanbrar1999 commented
With the other PRs are merged, this will boil down to a very small change within the prometheus_static directory. The overlap is not 100% though so this needs to be left open

2020-12-03 22:26 UTC, wyTrivail approved these changes
thanks!

2020-12-03 22:26 UTC, merged