Remove the spark-sample-app from the otel-test-framework
aws-observability/aws-otel-collector-test-framework pull request #515
Opened 2022-01-18 21:37 UTC by vasireddy99

This PR addresses the issue #497 

In-order to reduce the maintenance for [spark-sample app](https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/sample-apps/spark) from aws-otel-java-instrumentation into aws-otel-test-framework. Using sample image `public.ecr.aws/aws-otel-test/aws-otel-java-spark:latest` instead of dedupe.

This is a draft PR and waiting for approval of [sample-app PR](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/140).

2022-01-19 02:58 UTC, anuraaga approved these changes

2022-01-19 05:37 UTC, khanhntd approved these changes
So the whole point would be transferring all the sample apps to their corresponding aws-otel SDK. Therefore, reducing maintenance the sample app on aws-otel-test-framework correct? If that's the whole point, then it's good to me

2022-01-19 16:23 UTC, jefchien requested changes

2022-01-19 16:23 UTC, jefchien commented on terraform/testcases/otlp_mock/parameters.tfvars
> +sample_app_image = "public.ecr.aws/aws-otel-test/aws-otel-java-spark:latest"
You'll want to change it in more places than this one. There are a lot of testcases (`logzio_exporter_trace_mock`, `newrelic_exporter_metric_mock`, etc.) that use the default sample app, which is the spark app.

2022-01-19 17:23 UTC, sethAmazon commented
Does the spark latest support arm64 docker images?

2022-01-19 17:28 UTC, vasireddy99 commented
> Does the spark latest support arm64 docker images?

yes, it supports them[PR](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/140)

2022-01-19 17:29 UTC, jefchien commented
@vasireddy99 It looks like it's meant to, but the image on ECR https://gallery.ecr.aws/aws-otel-test/aws-otel-java-spark only has one.

2022-01-21 20:02 UTC, vasireddy99 commented
Changing to draft till #526 is merged

2022-01-21 22:27 UTC, closed without merging

2022-01-21 22:41 UTC, vasireddy99 commented
Closed due to rebasing issues. created [#527](https://github.com/aws-observability/aws-otel-test-framework/pull/527/files)