Remove deprecated `awsprw`exporter testcases
aws-observability/aws-otel-collector-test-framework pull request #787
Opened 2022-08-12 21:51 UTC by vasireddy99

**Description:**

This PR is created to remove deprecated `awsprometheusremotewrite` exporter test cases.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-12 21:55 UTC, erichsueh3 reviewed
This should remove mention of `_awsprw` tests as well in the `batchTestGenerator` tool

2022-08-12 22:28 UTC, erichsueh3 approved these changes

2022-08-12 22:28 UTC, erichsueh3 commented on tools/batchTestGenerator/internal/mock_test_data/eksoperatorarm64test.json
> +        		},
Can you also fix the spacing for L8-10 here, it seems to be tabs instead of spaces

2022-08-15 16:18 UTC, bryan-aguilar requested changes
This can only be merged after the component is removed from the ADOT Collector build.

2022-08-16 17:31 UTC, vasireddy99 commented
This PR needs to be merged prior to merging: https://github.com/aws-observability/aws-otel-collector/pull/1414

2022-08-16 17:34 UTC, bryan-aguilar commented
Is this required for the PR Build to pass?

2022-08-16 17:48 UTC, vasireddy99 commented
yeah, the changes in the mock tests have taken place in this PR.

2022-08-17 14:35 UTC, bryan-aguilar approved these changes

2022-08-17 16:20 UTC, merged